/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectoadministracion;

/**
 *
 * @author jesus
 */
public class InformadorDeTramites extends javax.swing.JFrame {
    
    public InformadorDeTramites() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JTramite = new javax.swing.JComboBox<>();
        btnTramite = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setResizable(false);

        jLabel1.setText("Informador de tramites");

        jLabel2.setText("Selecciona un tramite para obtener mas información");

        JTramite.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Proceso de inscripcion/educacion superior", "INE", "RFC", "Cartilla militar", "Rectificacion de Acta" }));

        btnTramite.setText("Seleccionar");
        btnTramite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTramiteActionPerformed(evt);
            }
        });

        jLabel4.setText("Informacion Necesaria para el tramite.");

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel5.setText("Para que sirve el tramite");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JTramite, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnTramite))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(128, 128, 128))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154))))
            .addGroup(layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTramite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTramite))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTramiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTramiteActionPerformed
        String InfoTramite = JTramite.getSelectedItem().toString();
        
        switch (InfoTramite){
            case "INE":
                jLabel3.setText("Credencial Para Votar(INE)");
                jTextArea2.setText("La INE sirve como identificación oficial, para abrir cuentas bancarias,\nefectuar trámites gubernamentales, inscribirse en instituciones educativas, \nrealizar trámites notariales y servir como identificación general para actividades para las cuales \nla mayoría de edad sea un requisito.");
                
                jTextArea1.setText("Documento que acredite tu nacionalidad."
                        + "\n-Acta de Nacimiento "
                        + "\n-Carta de certificado de Naturalización"
                        + "\n\nIdentificación con fotografia" 
                        + "\n-Cartilla del Servicio Militar Nacional"
                        + "\n-Pasaporte Vigente"
                        + "\n-Cédula Profesional"
                        + "\n-Licencia o Permiso de Conducir Vigente"
                        + "\n\nComprobante de domicilio(Comprobante vigente no mayor a 3 meses)"
                        + "\nServicios de impuestos Públicos."
                        + "\n-Predial \n-Luz \n-Agua"
                        + "\nServicio de impuestos privados. \n-Telefono \n-Señal de television \n-Gas"
                        + "\nEstados de cuenta. \n-Bancarios \n-Departamentales \n-Credito Hipotecario \n-Sistema de Ahorro para el retiro \n-Copia certificada de escrituras de propiedad inmobilaria "
                        + "\nOtros documentos aceptados como comprobante de domicilio. \n-Contrato de arrendamiento \n-Contrato de servicio publico \n-Constancia de numero oficial \n-Certificado de inscripcion de servicio publico de la propiedad");
                break;
            case "RFC":
                jLabel3.setText("Registro de Contribuyente(RFC)");
                jTextArea2.setText("El RFC sirve como identificación fiscal, como requisito para ser contratado en un empleo formal, \npara trámites bancarios, emisión de facturas, \nacceso a servicios gubernamentales y programas sociales y para verificar \nla consistencia de tu actividad económica.");
                
                jTextArea1.setText("Acta de Nacimiento o CURP"
                        + "\n\nIdentificación Oficial con fotografía" 
                        + "\n-Cartilla del Servicio Militar Nacional"
                        + "\n-Pasaporte Vigente"
                        + "\n-Cédula Profesional"
                        + "\n-Licencia o Permiso de Conducir Vigente"
                        + "\n\nComprobante de domicilio(Comprobante vigente no mayor a 3 meses)"
                        + "\nServicios de impuestos Públicos."
                        + "\n-Predial \n-Luz \n-Agua"
                        + "\nServicio de impuestos privados. \n-Telefono \n-Señal de television \n-Gas"
                        + "\nEstados de cuenta. \n-Bancarios \n-Departamentales \n-Credito Hipotecario \n-Sistema de Ahorro para el retiro \n-Copia certificada de escrituras de propiedad inmobilaria" 
                        + "\nOtros documentos aceptados como comprobante de domicilio. \n-Contrato de arrendamiento \n-Contrato de servicio publico \n-Constancia de numero oficial \n-Certificado de inscripcion de servicio publico de la propiedad"
                        + "\n\ncorreo electrónico personal válido \n\nacuse de prerregistro del RFC en caso de haber realizado el trámite en línea previamente");
                 break;
            case "Cartilla militar":
                jLabel3.setText("Cartilla Militar");
                jTextArea2.setText("La cartilla militar sirve como acreditación del servicio militar, identificación oficial, \nrequisito laboral y como formación de reservas del ejército.");
                jTextArea1.setText("Acta de Nacimiento certificada \n\nCURP"
                + "\nIdentificación oficial con fotografia"
                + "\n-Cartilla del Servicio Militar Nacional"
                + "\n-Pasaporte Vigente"
                + "\n-Cédula Profesional"
                + "\n-Licencia o Permiso de Conducir Vigente"
                + "\n\nComprobante de domicilio(Comprobante vigente no mayor a 3 meses)"
                + "\nServicios de impuestos Públicos."
                + "\n-Predial \n-Luz \n-Agua"
                + "\nServicio de impuestos privados. \n-Telefono \n-Señal de television \n-Gas"
                + "\nEstados de cuenta. \n-Bancarios \n-Departamentales \n-Credito Hipotecario \n-Sistema de Ahorro para el retiro \n-Copia certificada de escrituras de propiedad inmobilaria" 
                + "\nOtros documentos aceptados como comprobante de domicilio. \n-Contrato de arrendamiento \n-Contrato de servicio publico \n-Constancia de numero oficial \n-Certificado de inscripcion de servicio publico de la propiedad "
                + "\n\ncomprobante del grado máximo de estudios"
                + "\n\nCuatro fotografías recientes (no digitalizadas) de 35 X 45 mm., de frente a color o blanco \ny negro, con fondo blanco, con ropa clara, sin retoque, \nque las facciones de la persona interesada se distingan con claridad,\nsin tocado (gorra, sombrero, etc.), sin lentes, con las orejas descubiertas, \nsin aretes u otros objetos colocados en el rostro mediante perforaciones, \nel color de cabello deberá ser natural sin teñir en colores llamativos, \ndel nacimiento normal del cabello al borde inferior de la barbilla, deben medir 21 mm."      
                + "\n\nPara el personal masculino con el bigote recortado hasta la comisura de los labios, \nel corte de cabello será “casquete corto”, sin barba y patillas recortadas."
                + "\n\nPara el personal femenino será con el cabello recogido, sin fleco y sin maquillaje.");
                break;
            case "Proceso de inscripcion/educacion superior":
                jLabel3.setText("Proceso de inscripción en Educuación Superior(ITH)");
                jTextArea2.setText("Un proceso de inscripción en una institución de educación superior sirve para formalizar el \ningreso o continuidad académica del estudiante al registrarse para un período académico, \nasignar asignaturas y cumplir con los requisitos administrativos y financieros de la institución. \nEste proceso oficializa la matrícula, permite el acceso a los cursos y servicios de la institución y \nformaliza el historial académico del alumno. ");
                jTextArea1.setText("Realiza la inscripción en linea antes de estar en proceso de inscripción."
                + "\nDespues de realizar la inscripción en linea necesitaras:"
                + "\n\nPago de inscripción"
                + "\n\nDescargar solicitud de admisión"
                + "\n\nDescargar ficha de ingreso en formato PDF"
                + "\n\nTener la siguiente documentación escaneadas, en copia y fisicas:"
                + "\n-Certificado de Bachillerato o Cardex"
                + "\n-Acta de nacimiento"
                + "\n-CURP(Clave Única de Registro Unica o de Población)"
                + "\n-Recibo de Pago por Inscripción"
                + "\n-Cuatro Fotografias tamaño infantil recientes"
                + "\n-Certificado Médico"
                + "\n-Registro IMSS"
                + "\n-Contrato con el estudiante lleno(Normalmente te aparece en formato PDF \nal realizar el pago de inscripción)");
                break;
            case "Rectificacion de Acta":
                jLabel3.setText("Rectificación de Acta de nacimiento");
                jTextArea2.setText("Se solicita cuando el acta presenta algún error de omisión, \n(fecha de nacimiento, lugar de registro, lugar de nacimiento, apellido materno, etc.)\n ortográfico o gramatical.");
                jTextArea1.setText("Acta de nacimiento original y una copia"
                + "\nCurp"
                + "\n\nIdentificación Oficial Vigente"
                + "\n\nIdentificación oficial con fotografia"
                + "\n-Cartilla del Servicio Militar Nacional"
                + "\n-Pasaporte Vigente"
                + "\n-Cédula Profesional"
                + "\n-Licencia o Permiso de Conducir Vigente"
                + "\n\nCopia certificada del libro de registro original del acta de nacimiento"
                + "\n\nPara corregir nombres de padres, abuelos o apellidos"
                + "\n-Actas de nacimiento de padres o abuelos."
                + "\n-Constancia de origen."
                + "\n\nComprobante de domicilio(Comprobante vigente no mayor a 3 meses)"
                + "\nServicios de impuestos Públicos."
                + "\n-Predial \n-Luz \n-Agua"
                + "\nServicio de impuestos privados. \n-Telefono \n-Señal de television \n-Gas"
                + "\nEstados de cuenta. \n-Bancarios \n-Departamentales \n-Credito Hipotecario \n-Sistema de Ahorro para el retiro \n-Copia certificada de escrituras de propiedad inmobilaria" 
                + "\nOtros documentos aceptados como comprobante de domicilio. \n-Contrato de arrendamiento \n-Contrato de servicio publico \n-Constancia de numero oficial \n-Certificado de inscripcion de servicio publico de la propiedad"); 
        }
    }//GEN-LAST:event_btnTramiteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JTramite;
    private javax.swing.JButton btnTramite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
